version: "3.8"
services:
  site:
    image: ruby:3.2
    working_dir: /site
    volumes:
      - ./:/site
      - bundle-cache:/usr/local/bundle
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      JEKYLL_ENV: development
    command: >
      bash -lc "
        apt-get update &&
        apt-get install -y build-essential git &&
        gem install bundler &&
        bundle config set path '/usr/local/bundle' &&
        bundle install &&
        bundle exec jekyll serve --livereload --host 0.0.0.0 --baseurl ''
      "
volumes:
  bundle-cache:
