version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    container_name: vdt-jekyll
    command: jekyll serve --watch --force_polling --incremental
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - jekyll_data:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll_data:
